### ISSUE TITLE
Can I use your code and make an open source Project?

### ISSUE THREAD

**Issue by ThirteenIce2973** [Huniko519/Eoorox-Gaming-Esport-HTML#1]
Hello,

The thing is, I just started using github, and when I was looking for HTML templates on the Internet, I found that your template just met my needs, so I modified these open source codes again on this basis.

Due to the lack of thought at the time, I haven't thought of the original author's Github copyright issue, so I would like to ask for your opinion here.

After this, I looked up some information about copyright online, but I found that you did not claim your LICENSE in your open source project.

I modified some code based on your HTML template, just use it to make a blog-like website to introduce us, for learning and communication, that's all, NOT for commercial use.
You can check out the projects I've done: https://github.com/HoBoxz/Three-Musketeers

If this violates your rights, I can add your copyright notice to the footer (haven't written any information about you yet, you can ask me to add it), or close this site.

Since this site doesn't have any about you yet, I won't put any claims about you on the page until you instruct me.

If you can let me open source use (Write your information in the footer ), I will be very grateful, thank you for your understanding and support.

The above are all translated using Google Translate, there may be some errors, sorry for the inconvenience brought to you.
Source language: Chinese.

Thanks,
HoBoxz
Aug 27, 2022  China Standard Time.

**Comment by devcrafta** [comment]
Hi @ThirteenIce2973.
Sorry for the late reply.
Feel free to use my source code.
This is open source.
:)

**Comment by ThirteenIce2973** [comment]
I close it because I think there is no response.&nbsp;It's all right now

Thank you very much for your support!

Believe in youself, let's make progress together!






 &nbsp; &nbsp; Engineer Justin Ho

 ***@***.***

Nothing is impossible, to a willing heart.






                       
原始邮件
                       
                     

发件人："Huniko"< ***@***.*** &gt;;

发件时间：2023/1/30 17:36

收件人："huniko519/Eoorox-Gaming-Esport-HTML"< ***@***.*** &gt;;

抄送人："Justin Ho"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [huniko519/Eoorox-Gaming-Esport-HTML] Can I use your code andmake an open source Project? (Issue #1)




 
Hi @ThirteenIce2973.
 Sorry for the late reply.
 Feel free to use my source code.
 This is open source.
 :)

**Comment by ThirteenIce2973** [comment]
Hello,
I'm sorry to cause you confusion. I close it because I think there is no response. But it's all right now.
**Thank you very much for your support!**
_**_Believe in youself, let's make progress together!_**_
 🙂

**Comment by devcrafta** [comment]
Great....

**Comment by ThirteenIce2973** [comment]
I have put your project link on my repository "README.md" and the footer of the website tmes.eu.org.
**Thank you again for your open source!**
**Wish you work successfully, have a good day and stay safe!**

**Comment by devcrafta** [comment]
You too...
